### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRT#2] opened 2024-03-18 18:33 UTC
Building on Linux doesn't work.

==== Building hiprt02003 (debug_x64) ====
BatchBuilder.cpp
In file included from ../hiprt/impl/BatchBuilder.h:29,
                 from ../hiprt/impl/BatchBuilder.cpp:26:
../hiprt/impl/Context.h:26:10: fatal error: Orochi/Orochi.h: No such file or directory
   26 | #include <Orochi/Orochi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Orochi exists in the contrib/ directory.

**Comment by ScatteredRay** [comment] 2024-04-05 17:12
FWIW, I don't get the same issue locally, the include seems to be set in the premake here:
```
    externalincludedirs { "./contrib/Orochi/" }
```
Are you sure the Orochi submodule is properlly cloned?

Perhaps further reproduction instructions will be helpful.

**Comment by ib00** [comment] 2024-04-05 19:31
Your fork compiles fine for me, but the official repository doesn't.

**Comment by ScatteredRay** [comment] 2024-04-05 19:31
Continuing, this is the same error I get when I don't successfully clone submodules. I'd say just do a 'git submodule update --init' but as I submitted in my other bug: https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/issues/3 that fails right now.

**Comment by RichardGe** [comment] 2024-04-10 22:36
I just removed the private submodule.
My understanding is that it was what was causing this Linux build error.
I'll assume this is fixed with:
https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/pull/5
Please if you still have building error, re-open the ticket, or create a new one.

**Closed by RichardGe** 2024-04-10 22:36 UTC

**Comment by ib00** [comment] 2024-04-11 14:56
Thank you! The main branch compiles fine now on linux.
